### ISSUE TITLE
Thank you very much for sharing your work. I am asking for the weights.thank you 

### ISSUE THREAD

**Issue by SongLongZhang** [BCV-Uniandes/AUNets#1]

**Comment by affromero** [comment]
Thanks for your interest in our work. I am uploading the weights for our best network (OF-Horizontal), but it is taking more than expected. As soon as I have the link, I'll let you know here.

**Comment by affromero** [comment]
You can find a temporal link to the weights here: http://157.253.243.8/weights/AUNets
